on:
  push:
name: Test Extension
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test -- --verbose